# Generated by Django 5.0.1 on 2024-02-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Global_Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={},
        ),
        migrations.RemoveField(
            model_name='sales',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='name',
        ),
    ]
