# Generated by Django 5.0.1 on 2024-02-12 14:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global_Core', '0002_alter_sales_options_remove_sales_added_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'permissions': [('view_own_sales', 'Can view own sales')]},
        ),
        migrations.AddField(
            model_name='sales',
            name='acc_user_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Account User Name'),
        ),
        migrations.AddField(
            model_name='sales',
            name='account_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Account Address'),
        ),
        migrations.AddField(
            model_name='sales',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name on Account'),
        ),
        migrations.AddField(
            model_name='sales',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='sales',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='sales',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='sales',
            name='authorization',
            field=models.FileField(blank=True, null=True, upload_to='sales_files/', verbose_name='Authorization'),
        ),
        migrations.AddField(
            model_name='sales',
            name='btn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='BTN'),
        ),
        migrations.AddField(
            model_name='sales',
            name='calling_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Calling No'),
        ),
        migrations.AddField(
            model_name='sales',
            name='checking_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Checking No'),
        ),
        migrations.AddField(
            model_name='sales',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='Global_Core.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='sales',
            name='cus_dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_address',
            field=models.CharField(default=12, max_length=255, verbose_name='Customer Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_first_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Customer First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_last_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Customer Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Customer Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='sales',
            name='merchant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='Global_Core.merchants', verbose_name='Merchant Name'),
        ),
        migrations.AddField(
            model_name='sales',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('account', 'Account')], default=1, max_length=50, verbose_name='Payment Method'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='pin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pin'),
        ),
        migrations.AddField(
            model_name='sales',
            name='provider_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Provider Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='sales',
            name='ssn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='SSN'),
        ),
        migrations.AddField(
            model_name='sales',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_process', 'In-Process'), ('completed', 'Completed')], default=1, max_length=50, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
