# Generated by Django 5.0.1 on 2024-02-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Global_Core', '0002_card_card_to_be_used_card_gift_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_to_be_used',
        ),
        migrations.RemoveField(
            model_name='card',
            name='gift_card',
        ),
    ]
