# Generated by Django 5.0.1 on 2024-02-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global_Core', '0003_remove_card_card_to_be_used_remove_card_gift_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_to_be_used',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='gift_card',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('No', 'No')], default='no', max_length=10, null=True, verbose_name='is it a gift card'),
        ),
    ]
