# Generated by Django 4.2.10 on 2024-02-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Global_Core', '0005_paymentdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='account_address',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='checking_acc',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='checking_no',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='routing_no',
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name on Account')),
                ('checking_acc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Checking Account')),
                ('routing_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Routing #')),
                ('checking_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Checking No')),
                ('account_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Account Address')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Accounts', to='Global_Core.sales')),
            ],
        ),
    ]
