# Generated by Django 4.2.10 on 2024-02-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global_Core', '0006_remove_sales_account_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('account', 'Account')], default='card', max_length=50, verbose_name='Payment Method'),
        ),
    ]
