# Generated by Django 4.2.10 on 2024-02-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Global_Core', '0007_alter_bankaccount_options_alter_sales_payment_method'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Merchants',
            new_name='Gateway',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='merchant',
        ),
    ]
