# Generated by Django 4.2.10 on 2024-02-28 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Global_Core', '0008_rename_merchants_gateway_remove_sales_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255, verbose_name='Access Token')),
                ('login_id', models.CharField(max_length=255, verbose_name='Login Id/ Gateway Token')),
                ('Company_Name', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='dba_accounts', to='Global_Core.company', verbose_name='Company Name')),
                ('merchant_link', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_accounts_link', to='Global_Core.gateway', verbose_name='Merchant Name')),
            ],
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
