# Generated by Django 4.2.10 on 2024-02-29 08:10

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('Global_Core', '0010_alter_merchants_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='state',
            field=localflavor.us.models.USStateField(default=12, max_length=2, verbose_name='Customer State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='zip_code',
            field=models.CharField(default=12, max_length=255, verbose_name='Zip Code'),
            preserve_default=False,
        ),
    ]
