# Generated by Django 4.2.10 on 2024-02-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global_Core', '0012_remove_card_expire_date_card_expiry_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_to_be_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_to_be_used',
            field=models.BooleanField(default=False),
        ),
    ]
