# Generated by Django 4.2.10 on 2024-03-06 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Global_Core', '0015_customuser_name_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=255, verbose_name='Payment Method')),
                ('security', models.CharField(max_length=255, verbose_name='Security')),
                ('gateway', models.CharField(max_length=255, verbose_name='Gateway')),
                ('Merchant_Name', models.CharField(max_length=255, verbose_name='Merchant')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Invoice', to='Global_Core.sales')),
            ],
        ),
    ]
