# Generated by Django 4.2.10 on 2024-03-13 10:48

import Global_Core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Global_Core', '0016_alter_customuser_name_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_no',
            field=models.CharField(blank=True, max_length=255, validators=[Global_Core.models.validate_credit_card_number], verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='merchants',
            name='merchant_link',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_accounts_link', to='Global_Core.gateway', verbose_name='Gateway Name'),
        ),
    ]
