# Generated by Django 4.2.10 on 2024-03-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global_Core', '0017_alter_card_card_no_alter_merchants_merchant_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
